#' Ask ChatGPT Completions Endpoint
#'
#' @param prompt The prompt to generate completions for.
#' @param openai_api_key OpenAI's API key.
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' ask_chatgpt("What do you think about R language?")
#' }
ask_chatgpt <- function(prompt, openai_api_key = Sys.getenv("OPENAI_API_KEY")){
  cat(gpt_get_completions(prompt, openai_api_key)$choices[[1]]$text)
}
