#' Ask ChatGPT
#'
#' Note: See also `reset_chat_session`.
#'
#' @param question The question to ask ChatGPT.
#' @param session_id The ID of the session to be used. We can have different conversations by using
#'   different session IDs.
#' @param openai_api_key OpenAI's API key.
#' @param images A list of images to attach to the question. It could be a list of URLs or paths.
#'
#' @examples
#' \dontrun{
#' cat(ask_chatgpt("What do you think about R language?"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
ask_chatgpt <- function(question, session_id = "1", openai_api_key = Sys.getenv("OPENAI_API_KEY"),
                        images = NULL) {
  # Get the existing chat session messages, and add the new message.
  chat_session_messages <- append(get_chat_session(session_id), list(
    list(role = "user", content = build_prompt_content(question, images))
  ))
  # Send the query to ChatGPT.
  chat_gpt_reply <- parse_response(
    gpt_get_completions(question, openai_api_key, chat_session_messages)
  )
  chat_session_messages <- append(chat_session_messages, list(
    list(role = "assistant", content = chat_gpt_reply)
  ))
  # Update the chat session messages with the new question and the reply.
  reset_chat_session(chat_session_messages, session_id)
  chat_gpt_reply
}
