#' ChatGPT: Comment Code
#'
#' @param code The code to be commented by ChatGPT.
#'
#' @examples
#' \dontrun{
#' cat(comment_code("for (i in 1:10) {\n  print(i ** 2)\n}"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
comment_code <- function(code = clipr::read_clip(allow_non_interactive = TRUE)) {
  prompt <- paste0('Add inline comments to the following R code: "', paste(gsub('"', "'", code), collapse = "\n"), '"')
  parse_response(gpt_get_completions(prompt))
}
