#' ChatGPT: Complete Code
#'
#' @param code The code to be completed by ChatGPT.
#'
#' @examples
#' \dontrun{
#' cat(complete_code("# A function to square each element of a vector\nsquare_each <- function("))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
complete_code <- function(code) {
  prompt <- paste0('Complete the following R code: "', code, '"')
  parse_response(gpt_get_completions(prompt))
}
