#' ChatGPT: Custom Prompt
#'
#' @param code The code to be appended to your custom prompt prior to sending to
#'  ChatGPT. If not provided, it will use what's copied on the clipboard.
#'
#' @importFrom clipr read_clip
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
custom_prompt <- function(code = clipr::read_clip(allow_non_interactive = TRUE)) {
  code <- paste(gsub('"', "'", code), collapse = "\n")
  prompt_prefix <- rstudioapi::showPrompt("Custom Prompt", "What prompt would you like to prepend to your selected code?", )
  if(is.null(prompt_prefix)){
    return(NA)
  }
  prompt <- paste0(prompt_prefix, ': "', code, '"')
  parse_response(gpt_get_completions(prompt))
}
