# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [master, develop]

name: code-review-gpt

jobs:
  code-review-gpt:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: code-review
        env:
          URL: ${{ github.event.issue.comments_url }}
        run: |
          print(GITHUB_BASE_REF <- Sys.getenv("GITHUB_BASE_REF"))
          print(GITHUB_HEAD_REF <- Sys.getenv("GITHUB_HEAD_REF"))
          print(GITHUB_TOKEN <- Sys.getenv("GITHUB_PAT"))
          diff <- system(
            paste0("git diff ", GITHUB_BASE_REF, "..", GITHUB_HEAD_REF), intern = TRUE
          )
          prompt <- paste(
            "Between sextuple quotes is a GitHub PR.",
            "Please perform a code review on it.",
            "Only notify if you find any issues.",
            "If possible, specify on which files and lines you find the issues.",
            '""""""',
            paste(diff, collapse = "\n"),
            '""""""',
            sep = "\n"
          )
          system(paste0('
            curl \
              -X POST $URL \
              -H "Content-Type: application/json" \
              -H "Authorization: token ', GITHUB_TOKEN, '" \
              --data \\'{ "body": "blah blah" }\\'
          '))
        shell: Rscript {0}
