# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [master, develop]

name: code-review-gpt

jobs:
  code-review-gpt:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: *.R

      - name: code-review
        if: env.GIT_DIFF
        run: echo '${{ env.GIT_DIFF }}' | jq .
